apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-deployment.yaml
  - prod_patches/git-hpa.yaml
  
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: git
    path: prod_patches/git-prod.yaml