apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: env
        imagePullPolicy: Never
        image: git
        name: git
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}